baseURL = "https://alex.dinnouti.com/"
languageCode = 'en-us'
title = 'Alex Tech Blog'
theme = "dinnouti"
pygmentsUseClasses=true
googleAnalytics = "UA-924299-15"

[author]
name = "Alex Dinnouti"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5