baseURL = "https://alex.dinnouti.com/"
languageCode = "en-us"
title = "Alex Tech Blog"
pygmentsUseClasses=true
googleAnalytics = "UA-924299-15"

[build]
  writeStats = true

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"